import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { CardHandler } from "@/components/card-handler.component";
import { getHotCoffees } from "@/services/coffeeApi.service";
import { Three } from "@/components/three.component";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  getHotCoffees();
  return (
    <>
      <Head>
        <title>Coffee app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <CardHandler /> */}
        <Three />
      </main>
    </>
  );
}
